### ISSUE TITLE
[CoderSchool Android] Project 3 - Simple Twitter Client - Ready for review

### ISSUE THREAD

**Issue by yasuosm** [yasuosm/coderschool-project3-twitter-client#1]
My app is complete. Please review. /cc @coderschoolreview

**Comment by hoanle** [comment]
@yasuosm 

:+1: Nice work. A few notes after checking out the code:
- App crashes when there is no connection
- Some features are not implemented (Reply)
- Good to see you were able to format the timestamp cleanly
- Nice to see you used the SwipeRefreshLayout for easy timeline refreshes
- Good to see you refreshed the timeline after composing a new tweet. You should scroll the list to the top so that user can see the new posted tweet 
- Nice touch with the character count being displayed while the user composes a tweet
- Glad to see you made the compose activity into a dialog instead
- Consider adding local persistence of tweets by using ActiveAndroid in the Tweet and User. See the persistence guide and this other guide for more details.
- There are some unnecessary class, for example: LinkifiedTextView. Use TextView with autoLink="web" (or "all") can do what you want. 
- To set color for button, image such as ibtnRetweet, ibtnFavorite, you can create a Drawable Selector, do not need to set by code in runtime 

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.

**Comment by yasuosm** [comment]
@hoanle 
Thank you for your review :smiley:
